const SAVE_KEY='levelUpCurrenciesV2';
const fresh=()=>({level:1,xp:0,lifetimeXp:0,runXp:0,totalClicks:0,highestLevel:1,energy:0,knowledge:0,crystals:0,totalCrystals:0,essence:0,energyUp:{},knowledgeUp:{},crystalUp:{},essenceUp:{},playSeconds:0,lastSave:Date.now(),compact:true,reducedMotion:false});
const layers={
 energy:[
  {id:'channel',name:'Stronger Channel',icon:'ϟ',desc:'+1 Energy per channel',base:8,scale:1.8,currency:'energy'},
  {id:'battery',name:'Energy Battery',icon:'▰',desc:'+0.25 automatic Energy/sec',base:20,scale:1.9,currency:'energy'},
  {id:'surge',name:'XP Surge',icon:'▲',desc:'Multiply all XP by 1.5×',base:35,scale:2.5,currency:'energy'},
  {id:'engine',name:'Training Engine',icon:'»',desc:'Generate 20% of click XP/sec',base:90,scale:2.8,currency:'energy'}],
 knowledge:[
  {id:'memory',name:'Perfect Memory',icon:'◫',desc:'Double all XP',base:2,scale:2.4,currency:'knowledge'},
  {id:'theory',name:'Energy Theory',icon:'ϟ',desc:'Double all Energy gain',base:4,scale:2.7,currency:'knowledge'},
  {id:'research',name:'Passive Research',icon:'⌁',desc:'+0.05 Knowledge/sec',base:8,scale:3,currency:'knowledge'},
  {id:'formula',name:'Conversion Formula',icon:'×',desc:'Double Knowledge from studying',base:15,scale:3.2,currency:'knowledge'}],
 crystal:[
  {id:'facet',name:'Perfect Facet',icon:'◆',desc:'Triple XP and Energy',base:1,scale:2.5,currency:'crystals'},
  {id:'prism',name:'Knowledge Prism',icon:'◇',desc:'Triple Knowledge gain',base:2,scale:3,currency:'crystals'},
  {id:'core',name:'Crystal Core',icon:'●',desc:'Multiply all resources by level',base:4,scale:3.5,currency:'crystals'},
  {id:'preserve',name:'Preservation',icon:'∞',desc:'Start Crystal resets at +2 levels',base:8,scale:4,currency:'crystals'}],
 essence:[
  {id:'eternal',name:'Eternal Growth',icon:'∞',desc:'Multiply all production by 5×',base:1,scale:3,currency:'essence'},
  {id:'origin',name:'Higher Origin',icon:'▲',desc:'Start every reset +5 levels higher',base:2,scale:4,currency:'essence'},
  {id:'overflow',name:'Resource Overflow',icon:'✦',desc:'Triple every currency gain',base:5,scale:5,currency:'essence'},
  {id:'continuum',name:'Continuum',icon:'⌁',desc:'Double offline efficiency',base:12,scale:6,currency:'essence'}]
};
const unlocks=[{level:3,name:'Energy',page:'energy'},{level:8,name:'Knowledge',page:'knowledge'},{level:15,name:'Crystals',page:'crystals'},{level:25,name:'Essence',page:'essence'}];
const ranks=[{level:1,name:'Initiate'},{level:5,name:'Charged'},{level:10,name:'Scholar'},{level:15,name:'Crystallized'},{level:25,name:'Ethereal'},{level:40,name:'Infinite'}];
let state=fresh(),lastTick=performance.now();const $=id=>document.getElementById(id);
function req(l=state.level){return Math.ceil(5*Math.pow(1.5,l-1)*Math.pow(1+(l-1)/10,1.45))}
function fmt(n){if(!state.compact)return Math.floor(n).toLocaleString();if(n<1000)return Math.floor(n).toLocaleString();const u=['K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];let i=-1;while(n>=1000&&i<u.length-1){n/=1000;i++}return`${n>=100?n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2)}${u[i]}`}
function rank(){return[...ranks].reverse().find(r=>state.level>=r.level)||ranks[0]}
function up(layer,id){return state[`${layer}Up`][id]||0}function price(layer,item){return Math.ceil(item.base*Math.pow(item.scale,up(layer,item.id)))}
function essenceMult(){return Math.pow(5,up('essence','eternal'))*Math.pow(3,up('essence','overflow'))}
function crystalMult(){return Math.pow(3,up('crystal','facet'))*Math.pow(Math.max(1,state.level),up('crystal','core'))}
function xpMult(){return Math.pow(1.5,up('energy','surge'))*Math.pow(2,up('knowledge','memory'))*crystalMult()*essenceMult()}
function clickPower(){return(1+state.level*.2)*xpMult()}
function energyClick(){return(1+up('energy','channel'))*Math.pow(2,up('knowledge','theory'))*crystalMult()*essenceMult()}
function energyRate(){return up('energy','battery')*.25*Math.pow(2,up('knowledge','theory'))*crystalMult()*essenceMult()}
function knowledgeRate(){return up('knowledge','research')*.05*Math.pow(3,up('crystal','prism'))*essenceMult()}
function xpRate(){return clickPower()*up('energy','engine')*.2}
function studyGain(){return state.energy<100?0:Math.max(1,Math.floor(Math.pow(state.energy/100,.68)*Math.pow(2,up('knowledge','formula'))*Math.pow(3,up('crystal','prism'))*essenceMult()))}
function crystalGain(){return state.runXp<50000?0:Math.floor(Math.sqrt(state.runXp/50000)*Math.max(1,up('knowledge','memory')*.25+1))}
function essenceGain(){return state.level<25?0:Math.max(1,Math.floor(Math.pow((state.level-20)/5,1.3)+state.totalCrystals/15))}
function addXp(a){state.xp+=a;state.lifetimeXp+=a;state.runXp+=a;let gained=0;while(state.xp>=req()){state.xp-=req();state.level++;state.highestLevel=Math.max(state.highestLevel,state.level);gained++}if(gained)levelUp(gained)}
function clickXp(e){const a=clickPower();state.totalClicks++;addXp(a);floatText(e,`+${fmt(a)} XP`,'');render()}
function channel(e){const a=energyClick();state.energy+=a;floatText(e,`+${fmt(a)} ϟ`,'energy-float');render()}
function study(){const gain=studyGain();if(!gain)return;state.energy=0;state.knowledge+=gain;toast(`Converted your Energy into ${fmt(gain)} Knowledge`);render();save()}
function collectCrystals(){const gain=crystalGain();if(!gain||!confirm(`Crystallize this run for ${gain} Crystals? XP, levels, Energy, and Knowledge will reset.`))return;state.crystals+=gain;state.totalCrystals+=gain;resetLower('crystal');showPage('crystals');toast(`Collected ${gain} Crystals`);save();render()}
function collectEssence(){const gain=essenceGain();if(!gain||!confirm(`Collapse all lower layers for ${gain} Essence?`))return;state.essence+=gain;resetLower('essence');showPage('essence');toast(`Collected ${gain} Essence`);save();render()}
function resetLower(kind){const start=1+up('crystal','preserve')*2+up('essence','origin')*5;state.level=start;state.xp=0;state.runXp=0;state.energy=0;state.knowledge=0;state.energyUp={};state.knowledgeUp={};if(kind==='essence'){state.crystals=0;state.totalCrystals=0;state.crystalUp={}}}
function buy(layer,id){const item=layers[layer].find(i=>i.id===id),p=price(layer,item),currency=item.currency;if(state[currency]<p)return;state[currency]-=p;state[`${layer}Up`][id]=(state[`${layer}Up`][id]||0)+1;render();save()}
function floatText(e,text,extra){if(state.reducedMotion)return;const f=document.createElement('span');f.className=`float-xp ${extra}`;f.textContent=text;f.style.left=`${e.clientX}px`;f.style.top=`${e.clientY}px`;document.body.appendChild(f);setTimeout(()=>f.remove(),850)}
function levelUp(count){$('modalLevel').textContent=state.level;const unlocked=unlocks.find(u=>u.level===state.level);$('modalReward').textContent=unlocked?`${unlocked.name} currency unlocked!`:`XP requirement increased${count>1?` · ${count} levels gained`:''}`;$('levelModal').classList.add('show');clearTimeout(levelUp.timer);levelUp.timer=setTimeout(()=>$('levelModal').classList.remove('show'),1100);updateLocks();save()}
function renderLayer(layer,container){$(container).innerHTML=layers[layer].map(item=>{const lvl=up(layer,item.id),p=price(layer,item),currency=item.currency;return`<article class="upgrade-card"><div class="upgrade-icon">${item.icon}</div><div class="upgrade-copy"><strong>${item.name}</strong><small>${item.desc}</small><em>Level ${lvl}</em></div><button class="buy-btn" data-layer="${layer}" data-upgrade="${item.id}" ${state[currency]<p?'disabled':''}>UPGRADE<span class="currency-cost">${fmt(p)} ${currency.toUpperCase()}</span></button></article>`}).join('')}
function renderRewards(){let start=Math.max(1,state.level-2);$('rewardTrack').innerHTML=Array.from({length:5},(_,i)=>start+i).map(l=>{const unlock=unlocks.find(u=>u.level===l);return`<div class="reward-node ${l<state.level?'reached':l===state.level?'current':''}"><b>LV ${l}</b><span>${unlock?'✦':'+'}</span><small>${unlock?.name||'XP scaling'}</small></div>`}).join('')}
function render(){const required=req(),pct=Math.min(100,state.xp/required*100),r=rank();$('headerLevel').textContent=state.level;$('sideLevel').textContent=state.level;$('mainLevel').textContent=state.level;$('headerPower').textContent=fmt(clickPower());$('headerRate').textContent=fmt(xpRate());$('rankName').textContent=r.name;$('rankPill').textContent=r.name.toUpperCase();$('currentXp').textContent=fmt(state.xp);$('requiredXp').textContent=fmt(required);$('xpBar').style.width=`${pct}%`;$('xpPercent').textContent=`${pct.toFixed(1)}%`;$('clickPower').textContent=fmt(clickPower());$('buttonGain').textContent=fmt(clickPower());$('passivePower').textContent=fmt(xpRate());$('lifetimeXp').textContent=fmt(state.lifetimeXp);$('totalClicks').textContent=fmt(state.totalClicks);$('criticalClicks').parentElement.style.display='none';$('highestLevel').textContent=state.highestLevel;$('timePlayed').textContent=state.playSeconds<3600?`${Math.floor(state.playSeconds/60)}m`:`${Math.floor(state.playSeconds/3600)}h ${Math.floor(state.playSeconds%3600/60)}m`;const next=unlocks.find(u=>state.highestLevel<u.level);$('nextUnlockName').textContent=next?`${next.name} currency`:'All currencies unlocked';$('nextUnlockLevel').textContent=next?`Reach level ${next.level}`:'Build toward infinity';$('unlockProgress').style.width=next?`${Math.min(100,state.highestLevel/next.level*100)}%`:'100%';$('energyAmount').textContent=fmt(state.energy);$('energyRate').textContent=fmt(energyRate());$('energyClick').textContent=fmt(energyClick());$('knowledgeAmount').textContent=fmt(state.knowledge);$('knowledgeRate').textContent=fmt(knowledgeRate());$('studyText').textContent=studyGain()?`Spend ${fmt(state.energy)} Energy → ${fmt(studyGain())} Knowledge`:'Requires 100 Energy';$('studyButton').disabled=!studyGain();$('crystalAmount').textContent=fmt(state.crystals);const cg=crystalGain();$('crystalGainText').textContent=cg?`Reset for ${fmt(cg)} Crystals`:'Reach 50K run XP';$('crystalButton').disabled=!cg;const eg=essenceGain();$('essenceGain').textContent=fmt(eg);$('essenceAmount').textContent=fmt(state.essence);$('essenceButton').disabled=!eg;$('essenceButton').textContent=eg?`Collect ${fmt(eg)} Essence`:'Reach level 25 to collect Essence';renderRewards();renderLayer('energy','energyGrid');renderLayer('knowledge','knowledgeGrid');renderLayer('crystal','crystalGrid');renderLayer('essence','essenceGrid')}
function updateLocks(){document.querySelectorAll('.nav-btn[data-unlock]').forEach(btn=>{const open=state.highestLevel>=Number(btn.dataset.unlock);btn.classList.toggle('locked',!open);btn.querySelector('small').textContent=open?'Currency unlocked':`Unlocks at level ${btn.dataset.unlock}`})}
function showPage(id){const btn=document.querySelector(`[data-page="${id}"]`);if(btn?.classList.contains('locked')){toast(`Reach level ${btn.dataset.unlock} to unlock this currency`);return}document.querySelectorAll('.page,.nav-btn').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');btn?.classList.add('active')}
function save(show=false){state.lastSave=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(show)toast('Progress saved')}
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw)state={...fresh(),...JSON.parse(raw)};const away=Math.min(28800,(Date.now()-(state.lastSave||Date.now()))/1000),eff=Math.min(1,.5*Math.pow(2,up('essence','continuum')));if(away>30){const x=xpRate()*away*eff,e=energyRate()*away*eff,k=knowledgeRate()*away*eff;addXp(x);state.energy+=e;state.knowledge+=k;if(x+e+k>0)setTimeout(()=>toast(`Offline progress: +${fmt(x)} XP, +${fmt(e)} Energy, +${fmt(k)} Knowledge`),500)}}catch{state=fresh()}$('compactToggle').checked=state.compact;$('motionToggle').checked=state.reducedMotion}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2500)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]'),upgrade=e.target.closest('[data-upgrade]');if(nav)showPage(nav.dataset.page);if(upgrade)buy(upgrade.dataset.layer,upgrade.dataset.upgrade)});$('xpButton').onclick=clickXp;$('energyButton').onclick=channel;$('studyButton').onclick=study;$('crystalButton').onclick=collectCrystals;$('essenceButton').onclick=collectEssence;$('saveBtn').onclick=()=>save(true);$('settingsBtn').onclick=()=>$('settingsModal').showModal();
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!$('settingsModal').open&&!['INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();const r=$('xpButton').getBoundingClientRect();clickXp({clientX:r.left+r.width/2,clientY:r.top+r.height/2})}});$('compactToggle').onchange=e=>{state.compact=e.target.checked;render();save()};$('motionToggle').onchange=e=>{state.reducedMotion=e.target.checked;save()};$('exportBtn').onclick=()=>{navigator.clipboard.writeText(btoa(JSON.stringify(state)));toast('Save copied')};$('importBtn').onclick=()=>{const code=prompt('Paste your save code');if(!code)return;try{state={...fresh(),...JSON.parse(atob(code))};save();updateLocks();render();toast('Save imported')}catch{toast('Invalid save code')}};$('resetBtn').onclick=()=>{if(confirm('Erase all progression?')){localStorage.removeItem(SAVE_KEY);state=fresh();updateLocks();showPage('train');render();$('settingsModal').close();toast('Progress reset')}};
load();updateLocks();render();setInterval(()=>{const now=performance.now(),dt=Math.min(1,(now-lastTick)/1000);lastTick=now;addXp(xpRate()*dt);state.energy+=energyRate()*dt;state.knowledge+=knowledgeRate()*dt;state.playSeconds+=dt;render()},250);setInterval(()=>save(),10000);addEventListener('beforeunload',()=>save());
