const SAVE_KEY='idleGemsSaveV1';
const gemsData=[
  {name:'Quartz',level:1,color:'#a8eaff',value:1,rarity:'COMMON'}, {name:'Amethyst',level:5,color:'#bb7bff',value:2,rarity:'UNCOMMON'},
  {name:'Emerald',level:10,color:'#53e7a1',value:4,rarity:'RARE'}, {name:'Ruby',level:18,color:'#ff5f79',value:8,rarity:'RARE'},
  {name:'Sapphire',level:28,color:'#5f8dff',value:15,rarity:'EPIC'}, {name:'Topaz',level:42,color:'#ffc35f',value:28,rarity:'EPIC'},
  {name:'Diamond',level:60,color:'#f2fbff',value:55,rarity:'LEGENDARY'}, {name:'Voidstone',level:85,color:'#e15dff',value:120,rarity:'MYTHIC'}
];
const workerData=[
  {id:'pickers',name:'Gem Picker',icon:'⛏',base:10,gps:1.2,desc:'Carefully chips gems from the cavern wall.'},
  {id:'carts',name:'Crystal Cart',icon:'▣',base:90,gps:7.5,desc:'Hauls loose crystals around the clock.'},
  {id:'drills',name:'Prism Drill',icon:'⚙',base:800,gps:48,desc:'Bores through dense gemstone veins.'},
  {id:'lasers',name:'Laser Excavator',icon:'⌁',base:8500,gps:320,desc:'Cuts perfect gems with focused light.'},
  {id:'cores',name:'Quantum Core',icon:'◉',base:95000,gps:2300,desc:'Pulls crystals from neighboring realities.'},
  {id:'stars',name:'Star Forge',icon:'✦',base:1250000,gps:17000,desc:'Condenses starlight into flawless gems.'}
];
const upgradeData=[
  {id:'tools',name:'Hardened Tools',icon:'⛏',base:35,desc:'Double gems from every strike.',type:'click'},
  {id:'gloves',name:'Resonant Gloves',icon:'◇',base:300,desc:'Double gems from every strike.',type:'click'},
  {id:'training',name:'Crew Training',icon:'♟',base:1800,desc:'Double all worker production.',type:'gps'},
  {id:'lanterns',name:'Prismatic Lanterns',icon:'☼',base:12500,desc:'Double all gem production.',type:'all'},
  {id:'survey',name:'Deep Survey',icon:'⌖',base:110000,desc:'Triple all worker production.',type:'gps3'},
  {id:'alchemy',name:'Crystal Alchemy',icon:'✧',base:1100000,desc:'Triple all gem production.',type:'all3'}
];
const achievements=[
  {id:'first',name:'First Sparkle',desc:'Mine your first gem',test:s=>s.lifetime>=1}, {id:'hundred',name:'Pocketful of Gems',desc:'Mine 100 lifetime gems',test:s=>s.lifetime>=100},
  {id:'worker',name:'Help Wanted',desc:'Hire your first worker',test:s=>Object.values(s.workers).some(v=>v>0)}, {id:'thousand',name:'Gem Baron',desc:'Mine 10K lifetime gems',test:s=>s.lifetime>=1e4},
  {id:'deep',name:'Going Deeper',desc:'Reach cavern level 25',test:s=>s.level>=25}, {id:'army',name:'Full Crew',desc:'Own 50 workers',test:s=>Object.values(s.workers).reduce((a,b)=>a+b,0)>=50},
  {id:'million',name:'Cavern Tycoon',desc:'Mine 1M lifetime gems',test:s=>s.lifetime>=1e6}, {id:'ascended',name:'Prismatic Rebirth',desc:'Ascend for the first time',test:s=>s.shards>0}
];
const fresh=()=>({gems:0,lifetime:0,runLifetime:0,totalClicks:0,level:1,xp:0,workers:{},upgrades:{},achievements:[],shards:0,ascensions:0,started:Date.now(),lastSave:Date.now(),playSeconds:0,compact:true,reducedMotion:false});
let state=fresh(),combo=1,lastClick=0,sound=true,buyMode=1;
const $=id=>document.getElementById(id);
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw)state={...fresh(),...JSON.parse(raw)};const away=Math.min(8*3600,(Date.now()-(state.lastSave||Date.now()))/1000);if(away>60){const earned=getGps()*away*.5;state.gems+=earned;state.lifetime+=earned;state.runLifetime+=earned;setTimeout(()=>toast(`Welcome back! Your crew mined ${fmt(earned)} gems.`),500)}}catch(e){state=fresh()}applySettings()}
function save(show=false){state.lastSave=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(show)toast('Game saved!')}
function fmt(n){if(!state.compact)return Math.floor(n).toLocaleString();if(n<1000)return Math.floor(n).toLocaleString();const units=['K','M','B','T','Qa','Qi','Sx','Sp'];let i=-1;while(n>=1000&&i<units.length-1){n/=1000;i++}return `${n>=100? n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2)}${units[i]}`}
function discoveryMultiplier(){return 1+(gemsData.filter(g=>state.level>=g.level).length-1)*.08}
function clickPower(){let p=1*Math.pow(2,state.upgrades.tools||0)*Math.pow(2,state.upgrades.gloves||0);return p*allMultiplier()}
function allMultiplier(){return discoveryMultiplier()*(1+state.shards*.12)*Math.pow(2,state.upgrades.lanterns||0)*Math.pow(3,state.upgrades.alchemy||0)}
function getGps(){let base=workerData.reduce((sum,w)=>sum+(state.workers[w.id]||0)*w.gps,0);base*=Math.pow(2,state.upgrades.training||0)*Math.pow(3,state.upgrades.survey||0);return base*allMultiplier()}
function workerCost(w,owned=state.workers[w.id]||0){return Math.ceil(w.base*Math.pow(1.145,owned))}
function upgradeCost(u,owned=state.upgrades[u.id]||0){return Math.ceil(u.base*Math.pow(6.2,owned))}
function bulkQuote(item,type){const owned=type==='worker'?(state.workers[item.id]||0):(state.upgrades[item.id]||0),costAt=type==='worker'?workerCost:upgradeCost;let amount=buyMode==='max'?10000:Number(buyMode),cost=0,count=0;for(let i=0;i<amount;i++){const next=costAt(item,owned+i);if(cost+next>state.gems)break;cost+=next;count++}return{count,cost}}
function addGems(amount){state.gems+=amount;state.lifetime+=amount;state.runLifetime+=amount;state.xp+=amount;while(state.xp>=xpNeeded()){state.xp-=xpNeeded();state.level++;toast(`Cavern level ${state.level} reached!`)}checkAchievements()}
function xpNeeded(){return Math.floor(60*Math.pow(1.17,state.level-1))}
function mine(e){const now=Date.now();combo=now-lastClick<850?Math.min(5,combo+.15):1;lastClick=now;const amount=clickPower()*combo;addGems(amount);state.totalClicks++;if(!state.reducedMotion){const f=document.createElement('span');f.className='float-number';f.textContent=`+${fmt(amount)} ◆`;f.style.left=`${e.clientX}px`;f.style.top=`${e.clientY}px`;document.body.appendChild(f);setTimeout(()=>f.remove(),1000)}$('combo').textContent=`x${combo.toFixed(1)} combo`;$('combo').classList.add('show');clearTimeout(mine.comboTimer);mine.comboTimer=setTimeout(()=>$('combo').classList.remove('show'),1000);beep();render()}
function beep(){if(!sound)return;try{const ctx=beep.ctx||(beep.ctx=new AudioContext());const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=420+Math.random()*100;g.gain.setValueAtTime(.025,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.08);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.08)}catch(e){}}
function buyWorker(id){const w=workerData.find(x=>x.id===id),q=bulkQuote(w,'worker');if(q.count){state.gems-=q.cost;state.workers[id]=(state.workers[id]||0)+q.count;render();save()}}
function buyUpgrade(id){const u=upgradeData.find(x=>x.id===id),q=bulkQuote(u,'upgrade');if(q.count){state.gems-=q.cost;state.upgrades[id]=(state.upgrades[id]||0)+q.count;render();save()}}
function checkAchievements(){let changed=false;achievements.forEach(a=>{if(!state.achievements.includes(a.id)&&a.test(state)){state.achievements.push(a.id);changed=true;toast(`Achievement unlocked: ${a.name}`)}});if(changed)$('achievementDot').classList.remove('hidden')}
function renderCollection(){const found=gemsData.filter(g=>state.level>=g.level);$('collectionCount').textContent=`${found.length} / ${gemsData.length} found`;$('bestGem').textContent=found.at(-1).name;$('gemCollection').innerHTML=gemsData.map(g=>`<article class="gem-card ${state.level<g.level?'locked':''}"><span class="rarity">${state.level>=g.level?g.rarity:`LEVEL ${g.level}`}</span><span class="gem-icon" style="color:${g.color}">${state.level>=g.level?'◆':'?'}</span><strong>${state.level>=g.level?g.name:'Unknown Gem'}</strong><small>${state.level>=g.level?`${g.value}× crystal value`:'Descend deeper to discover'}</small></article>`).join('');const next=gemsData.find(g=>g.level>state.level);$('nextCavern').textContent=next?`${next.name} Vein`:'The Endless Geode';$('unlockText').textContent=next?`Reach cavern level ${next.level}`:'All known gems discovered';$('cavernProgress').style.width=next?`${Math.min(100,state.level/next.level*100)}%`:'100%'}
function renderWorkers(){$('workerList').innerHTML=workerData.map(w=>{const count=state.workers[w.id]||0,q=bulkQuote(w,'worker'),shown=q.count||1,cost=q.count?q.cost:workerCost(w);return `<article class="shop-card ${q.count?'affordable':''}"><div class="shop-icon">${w.icon}</div><div class="shop-copy"><strong>${w.name}</strong><small>${w.desc}</small><div class="owned">Owned ${count} · ${fmt(w.gps*allMultiplier())}/s each</div></div><button class="buy-button" data-worker="${w.id}" ${!q.count?'disabled':''}>Hire ×${shown}<span>◆ ${fmt(cost)}</span><small>+${fmt(w.gps*shown*allMultiplier())}/s</small></button></article>`}).join('')}
function renderUpgrades(){$('upgradeList').innerHTML=upgradeData.map(u=>{const count=state.upgrades[u.id]||0,q=bulkQuote(u,'upgrade'),shown=q.count||1,cost=q.count?q.cost:upgradeCost(u);return `<article class="shop-card ${q.count?'affordable':''}"><div class="shop-icon">${u.icon}</div><div class="shop-copy"><strong>${u.name}</strong><small>${u.desc}</small><div class="owned">Level ${count}</div></div><button class="buy-button" data-upgrade="${u.id}" ${!q.count?'disabled':''}>Upgrade ×${shown}<span>◆ ${fmt(cost)}</span></button></article>`}).join('')}
function renderAchievements(){$('achievementCount').textContent=`${state.achievements.length} / ${achievements.length} complete`;$('achievementList').innerHTML=achievements.map(a=>{const done=state.achievements.includes(a.id);return `<article class="achievement ${done?'done':''}"><div class="achievement-icon">${done?'✓':'◇'}</div><div><strong>${a.name}</strong><small>${a.desc}</small></div></article>`}).join('')}
function render(){const needed=xpNeeded();$('gems').textContent=fmt(state.gems);$('gps').textContent=fmt(getGps());$('clickPower').textContent=fmt(clickPower());$('totalMined').textContent=fmt(state.lifetime);$('level').textContent=state.level;$('depthLabel').textContent=Math.ceil(state.level/5);$('discoveryBonus').textContent=`+${Math.round((discoveryMultiplier()-1)*100)}%`;$('levelProgressText').textContent=`${fmt(state.xp)} / ${fmt(needed)}`;$('levelProgress').style.width=`${state.xp/needed*100}%`;$('playTime').textContent=state.playSeconds<3600?`${Math.floor(state.playSeconds/60)}m`:`${Math.floor(state.playSeconds/3600)}h ${Math.floor(state.playSeconds%3600/60)}m`;const gain=Math.floor(Math.sqrt(state.runLifetime/5e5));$('shardsGain').textContent=fmt(gain);$('ascendBoost').textContent=`+${Math.round(state.shards*12)}%`;const btn=$('ascendBtn');btn.disabled=gain<1;btn.textContent=gain<1?`Ascend at 500K expedition gems`:`Ascend for ${fmt(gain)} Prismatic Shards`;renderCollection();renderWorkers();renderUpgrades();renderAchievements()}
function ascend(){const gain=Math.floor(Math.sqrt(state.runLifetime/5e5));if(gain<1)return;if(!confirm(`Ascend for ${gain} Prismatic Shards? Your current mine will reset.`))return;const keep={shards:state.shards+gain,ascensions:state.ascensions+1,achievements:state.achievements,started:state.started,playSeconds:state.playSeconds,compact:state.compact,reducedMotion:state.reducedMotion,lifetime:state.lifetime};state={...fresh(),...keep};checkAchievements();save();render();toast('The cavern is reborn. Your power has grown!')}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2800)}
function applySettings(){document.body.classList.toggle('reduced-motion',state.reducedMotion);$('compactToggle').checked=state.compact;$('motionToggle').checked=state.reducedMotion}
document.addEventListener('click',e=>{const w=e.target.closest('[data-worker]'),u=e.target.closest('[data-upgrade]'),mode=e.target.closest('[data-mode]');if(w)buyWorker(w.dataset.worker);if(u)buyUpgrade(u.dataset.upgrade);if(mode){buyMode=mode.dataset.mode==='max'?'max':Number(mode.dataset.mode);document.querySelectorAll('.buy-mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode.dataset.mode));render()}});
$('mineButton').addEventListener('click',mine);$('saveBtn').onclick=()=>save(true);$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'♪':'×';toast(sound?'Sound on':'Sound off')};$('settingsBtn').onclick=()=>$('settingsModal').showModal();$('ascendBtn').onclick=ascend;
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!['INPUT','BUTTON'].includes(document.activeElement.tagName)&&!$('settingsModal').open){e.preventDefault();const r=$('mineButton').getBoundingClientRect();mine({clientX:r.left+r.width/2,clientY:r.top+r.height/2})}});
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active');if(t.dataset.tab==='achievements')$('achievementDot').classList.add('hidden')});
$('compactToggle').onchange=e=>{state.compact=e.target.checked;render();save()};$('motionToggle').onchange=e=>{state.reducedMotion=e.target.checked;applySettings();save()};
$('exportBtn').onclick=()=>{navigator.clipboard.writeText(btoa(JSON.stringify(state)));toast('Save copied to clipboard')};$('importBtn').onclick=()=>{const code=prompt('Paste your Idle Gems save code:');if(!code)return;try{state={...fresh(),...JSON.parse(atob(code))};save();render();toast('Save imported!')}catch(e){toast('That save code is invalid.')}};$('resetBtn').onclick=()=>{if(confirm('Permanently erase all Idle Gems progress?')){localStorage.removeItem(SAVE_KEY);state=fresh();render();$('settingsModal').close();toast('Progress reset')}};
load();render();let last=performance.now();setInterval(()=>{const now=performance.now(),dt=Math.min(1,(now-last)/1000);last=now;const production=getGps()*dt;if(production)addGems(production);state.playSeconds+=dt;render()},250);setInterval(()=>save(),10000);window.addEventListener('beforeunload',()=>save());
